apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
    task: jellyfin
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: jellyfin-web