apiVersion: v1
kind: Service
metadata:
  name: rffmpeg-workers
  namespace: jellyfin
spec:
  selector:
    app: rffmpeg-workers
    task: rffmpeg-workers
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: worker-ssh