apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-box-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi # this is just for testing, you should have your media elsewhere
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-subtitles
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-transcodes
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi